we continue to support Honeycomb, but without the action bar, since it causes 'java.lang.NoSuchMethodError: android.util.SparseBooleanArray.clone' in TransactionList